# Generated by Django 4.2.15 on 2024-08-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
