# Generated by Django 4.2.15 on 2024-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseApp', '0004_category_img_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='country',
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=1, upload_to='brand'),
            preserve_default=False,
        ),
    ]
