# Generated by Django 4.2.15 on 2024-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseApp', '0005_remove_brand_country_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
